<?php

namespace zikmont\InventarioBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvDocumentosRepository extends EntityRepository
{
    public function DevDocumentos()
    {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
                ->select('d.codigoDocumentoPk,d.nombre')
                ->from('zikmontInventarioBundle:InvDocumentos', 'd')
                ->orderBy('d.nombre');

        $objQuery = $query->getQuery();
        $arDocumentos = new \zikmont\InventarioBundle\Entity\InvDocumentos();
        $arDocumentos = $objQuery->getResult();
        
        return $arDocumentos;
    }
}