<?php

namespace zikmont\InventarioBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MovimientosDetallesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvMovimientosDetallesRepository extends EntityRepository {
    /**
     * Devuelve los detalles de inventario agrupados por Item, Bodega y Lote
     * @param type $dateFechaDesde
     * @param type $dateFechaHasta
     * @return type Objeto de tipo movimientos detalles
     */
    public function DevMovimientosDetallesInventario($indCodigoItem, $strFechaDesde = "", $strFechaHasta = "") {
        $objRepositorio = $this->getEntityManager();              
        $objQuery = $objRepositorio->createQueryBuilder()
                ->select('md.codigoItemFk, md.codigoBodegaFk, md.loteFk, SUM(md.cantidadOperada) as cantidadOperada')                
                ->from('zikmontInventarioBundle:InvMovimientosDetalles', 'md')                
                ->leftJoin("md.movimientoRel", "m")
                ->where('md.operacionInventario != 0 AND md.estadoAutorizado = 1 AND md.codigoItemFk = ' . $indCodigoItem)
                ->groupBy('md.codigoItemFk, md.codigoBodegaFk, md.loteFk'); 
                
        if ($strFechaDesde != "" && $strFechaDesde != NULL) 
            $objQuery->andWhere("m.fecha > '" . $strFechaDesde . "'");
        
        if ($strFechaHasta != "" && $strFechaHasta != NULL) 
            $objQuery->andWhere("m.fecha <= '" . $strFechaHasta . "'");        
        $objQuery = $objQuery->getQuery();
        return $objQuery->getResult();                
    }
    
    /**
     * Devuelve los detalles de movimiento sin agrupacion y que tienen operacion
     * @param type $dateFechaDesde
     * @param type $dateFechaHasta
     * @return type Objeto de tipo movimientos detalle
     */
    public function DevMovimientosDetallesOperacion($dateFechaDesde = "", $dateFechaHasta = "", $intItem = "") {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
                ->select('md.codigoDetalleMovimientoPk, md.codigoItemFk, md.codigoBodegaFk, md.loteFk, md.cantidadOperada')
                ->from('zikmontInventarioBundle:InvMovimientosDetalles', 'md')
                ->leftJoin("md.movimientoRel", "m")
                ->where('md.operacionInventario != 0 AND md.estadoAutorizado = 1')
                ->orderBy("m.fecha", 'ASC');
        
        if ($dateFechaDesde != Null && $dateFechaDesde != "")
            $query->andWhere("m.fecha >= '" . $dateFechaDesde . " 00:00:00'");
        
        if ($dateFechaHasta != Null && $dateFechaHasta != "")
            $query->andWhere("m.fecha <= '" . $dateFechaHasta . " 23:59:59'");
        
        if($intItem != "")
            $query->andWhere("md.codigoItemFk = " . $intItem);
        $objQuery = $query->getQuery();        
        return $objQuery->getResult();
    }
    
    /**
     * Devuelve los movimientos de inventario pero que generan costo
     * @param type $dateFechaDesde
     * @param type $dateFechaHasta
     * @param type $intItem
     * @return type
     */
    public function DevMovimientosDetallesGeneranCosto($dateFechaDesde = "", $dateFechaHasta = "", $intItem = "") {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
                ->select('md.codigoDetalleMovimientoPk, md.cantidadOperada, md.costo, doc.generaCostoPromedio')
                ->from('zikmontInventarioBundle:InvMovimientosDetalles', 'md')
                ->leftJoin("md.movimientoRel", "m")
                ->leftJoin("m.documentoRel", "doc")
                ->where('md.operacionInventario != 0 AND md.estadoAutorizado = 1')
                ->orderBy("m.fecha", 'ASC');
        
        if ($dateFechaDesde != Null && $dateFechaDesde != "")
            $query->andWhere("m.fecha >= '" . $dateFechaDesde . " 00:00:00'");
        
        if ($dateFechaHasta != Null && $dateFechaHasta != "")
            $query->andWhere("m.fecha <= '" . $dateFechaHasta . " 23:59:59'");
        
        if($intItem != "")
            $query->andWhere("md.codigoItemFk = " . $intItem);
        
        $objQuery = $query->getQuery();        
        return $objQuery->getResult();
    }    
    
    /**
     * Devuelve un array con todos los detalles de movimiento segun parametros
     * @param integer $codigoItem El codigo del producto a consultar
     * @param integer $codigoDocumento El codigo del documento  a consultar
     * @param integer $codigoTercero El codigo del tercero a consultar
     * @param string $lote El lote a consultar
     * @param string $bodega La bodega a Consultar
     * @param date $dateDesde La fecha desde donde se consultaran los detalles
     * @param date $dateHasta La fecha hasta donde se consultaran los detalles
     * @return array Detalles de Movimiento 
     */
    public function DevMovimientosDetalles($codigoItem = null,$codigoDocumento = null,$codigoTercero = null,$lote = null,$bodega = null,$dateDesde = null,$dateHasta = null) {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
                ->select('md')
                ->from('zikmontInventarioBundle:InvMovimientosDetalles', 'md')
                ->leftJoin("md.movimientoRel", "m")
                ->where('md.operacionInventario != :operacion')
                ->setParameter('operacion', 0)
                ->orderBy('m.fecha');

        if ($codigoItem != Null && $codigoItem != "")
            $query->andWhere('md.codigoItemFk = ' . $codigoItem);
        
        if ($codigoDocumento != Null && $codigoDocumento != "")
            $query->andWhere('m.codigoDocumentoFk = ' . $codigoDocumento);
        
        if ($codigoTercero != Null && $codigoTercero != "")
            $query->andWhere('m.codigoTerceroFk = ' . $codigoTercero);
        
        if ($lote != Null && $lote != "")
            $query->andWhere("md.loteFk ='" .$lote ."'");
        
        if ($bodega != Null && $bodega != "")
            $query->andWhere('md.codigoBodegaFk = ' . $bodega);
        
        if ($dateDesde != Null && $dateDesde != "") {
            $query->andWhere("m.fecha >='". $dateDesde." 00:00:00'");
        }
            
        if ($dateHasta != Null && $dateHasta != "")
            $query->andWhere("m.fecha <='". $dateHasta." 23:59:59'");
        
        $arMovimientosDetalles = $query->getQuery();

        return $arMovimientosDetalles->getResult();
    }

    public function DevMovDetItemLote($codigoMovimiento) {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
                ->select('md.codigoItemFk, md.codigoBodegaFk, md.loteFk, SUM(md.cantidad) as cantidad, item.itemServicio')
                ->from('zikmontInventarioBundle:InvMovimientosDetalles', 'md')
                ->where('md.codigoMovimientoFk = :codigoMovimientoFk')
                ->leftJoin('md.itemRel', 'item')
                ->groupBy('md.codigoItemFk, md.codigoBodegaFk, md.loteFk')
                ->setParameter('codigoMovimientoFk', $codigoMovimiento)
                ->getQuery();

        return $query->getResult();
    }

    /**
     * Devuelve resumen de detalles para contabilizar por cuenta de compras
     * @param integer $codigoMovimiento codigo del movimiento que se va a procesar.
     * */
    public function DevResumenCuentaCompras($codigoMovimiento) {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
                ->select('SUM(md.subTotal) as subTotal, item.cuentaCompras')
                ->from('zikmontInventarioBundle:InvMovimientosDetalles', 'md')
                ->leftJoin('md.itemRel', 'item')
                ->where('md.codigoMovimientoFk = :codigoMovimientoFk')
                ->groupBy('item.cuentaCompras')
                ->setParameter('codigoMovimientoFk', $codigoMovimiento)
                ->getQuery();

        return $query->getResult();
    }

    /**
     * Devuelve resumen de detalles para contabilizar por cuenta de compras
     * @param integer $codigoMovimiento codigo del movimiento que se va a procesar.
     * */
    public function DevResumenCuentaDevolucionCompras($codigoMovimiento) {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
                ->select('SUM(md.subTotal) as subTotal, item.cuentaDevolucionCompras')
                ->from('zikmontInventarioBundle:InvMovimientosDetalles', 'md')
                ->leftJoin('md.itemMD', 'item')
                ->where('md.codigoMovimientoFk = :codigoMovimientoFk')
                ->groupBy('item.cuentaDevolucionCompras')
                ->setParameter('codigoMovimientoFk', $codigoMovimiento)
                ->getQuery();

        return $query->getResult();
    }    
    
    /**
     * Devuelve resumen de detalles para contabilizar por cuenta de compras
     * @param integer $codigoMovimiento codigo del movimiento que se va a procesar.
     * */
    public function DevResumenCuentaVentas($codigoMovimiento) {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
                ->select('SUM(md.subTotal) as subTotal, item.cuentaIngreso')
                ->from('zikmontInventarioBundle:InvMovimientosDetalles', 'md')
                ->leftJoin('md.itemMD', 'item')
                ->where('md.codigoMovimientoFk = :codigoMovimientoFk')
                ->groupBy('item.cuentaCompras')
                ->setParameter('codigoMovimientoFk', $codigoMovimiento)
                ->getQuery();

        return $query->getResult();
    }    
    
    /**
     * Devuelve resumen de detalles para contabilizar por cuenta de compras
     * @param integer $codigoMovimiento codigo del movimiento que se va a procesar.
     * */
    public function DevResumenCuentaDevolucionVentas($codigoMovimiento) {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
                ->select('SUM(md.subTotal) as subTotal, item.cuentaDevolucionVentas')
                ->from('zikmontInventarioBundle:InvMovimientosDetalles', 'md')
                ->leftJoin('md.itemMD', 'item')
                ->where('md.codigoMovimientoFk = :codigoMovimientoFk')
                ->groupBy('item.cuentaDevolucionCompras')
                ->setParameter('codigoMovimientoFk', $codigoMovimiento)
                ->getQuery();

        return $query->getResult();
    }     
    
    /**
     * Devuelve resumen de detalles para contabilizar por cuenta de compras
     * @param integer $codigoMovimiento codigo del movimiento que se va a procesar.
     * */
    public function DevResumenCuentaCostoVentas($codigoMovimiento) {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
                ->select('SUM(md.costo * md.cantidad) as costo, item.cuentaCosto')
                ->from('zikmontInventarioBundle:InvMovimientosDetalles', 'md')
                ->leftJoin('md.itemMD', 'item')
                ->where('md.codigoMovimientoFk = :codigoMovimientoFk')
                ->groupBy('item.cuentaCosto')
                ->setParameter('codigoMovimientoFk', $codigoMovimiento)
                ->getQuery();

        return $query->getResult();
    }    
    
    /**
     * Devuelve resumen de detalles para contabilizar por cuenta de compras
     * @param integer $codigoMovimiento codigo del movimiento que se va a procesar.
     * */
    public function DevResumenCuentaInventario($codigoMovimiento) {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
                ->select('SUM(md.costo * md.cantidad) as costo, item.cuentaInventario')
                ->from('zikmontInventarioBundle:InvMovimientosDetalles', 'md')
                ->leftJoin('md.itemMD', 'item')
                ->where('md.codigoMovimientoFk = :codigoMovimientoFk')
                ->groupBy('item.cuentaCompras')
                ->setParameter('codigoMovimientoFk', $codigoMovimiento)
                ->getQuery();

        return $query->getResult();
    }    
    
    /**
     * Devuelve resumen de detalles para contabilizar por cuenta de iva
     * @param integer $codigoMovimiento codigo del movimiento que se va a procesar.
     * @return double $subTotalBaseIva subtotal de los registros con iva
     * */
    public function DevBaseIva($codigoMovimiento) {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
                ->select('SUM(md.subTotal) as subTotal')
                ->from('zikmontInventarioBundle:InvMovimientosDetalles', 'md')
                ->where('md.codigoMovimientoFk = :codigoMovimientoFk AND md.porcentajeIva > 0')
                ->setParameter('codigoMovimientoFk', $codigoMovimiento)
                ->getQuery();
        $arMovimientosDetalles = $query->getResult();
        return (double) $arMovimientosDetalles[0]['subTotal'];
    }

    /**
     * Devuelve un listado con los pedidos pendientes de un producto
     * @param intger $codigoProducto
     * @return array 
     */
    public function DevPedidosPendientes($codigoProducto) {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
                ->select('md.cantidad, movimientos.fecha, movimientos.numeroMovimiento')
                ->from('zikmontInventarioBundle:InvMovimientosDetalles', 'md')
                ->leftJoin('md.movimientoRel', 'movimientos')
                ->leftJoin('movimientos.terceroRel', 'terceros')
                ->where('md.codigoItemFk = :codigoItemFk AND md.estadoAutorizado = 1 AND movimientos.codigoDocumentoFk = 4')
                ->setParameter('codigoItemFk', $codigoProducto)
                ->getQuery();

        $arPedidosPendientes = $query->getResult();
        return $arPedidosPendientes;
    }
    
    /**
     * Devuelve un listado con las ordenes de compra pendientes de un producto
     * @param intger $codigoProducto
     * @return array 
     */
    public function DevOrdenesPendientes($codigoProducto) {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
                ->select('md.cantidad')
                ->from('zikmontInventarioBundle:InvMovimientosDetalles', 'md')
                ->leftJoin('md.movimientoRel', 'movimientos')
                ->where('md.codigoItemFk = :codigoItemFk AND md.estadoAutorizado = 1 AND movimientos.codigoDocumentoFk = 4')
                ->setParameter('codigoItemFk', $codigoProducto)
                ->getQuery();

        $arPedidosPendientes = $query->getResult();
        return $arPedidosPendientes;
    }
    
    /**
     * 
     * @param integer $codigoMovimientoDetalle 
     */
    public function EstableceLoteMovimientoDetalle($codigoMovimientoDetalle) {
        $em = $this->getEntityManager();
        $arMovimientoDetalle = new \zikmont\InventarioBundle\Entity\InvMovimientosDetalles();
        $arMovimientoDetalle = $em->getRepository('zikmontInventarioBundle:InvMovimientosDetalles')->find($codigoMovimientoDetalle);
        $arLotes = new \zikmont\InventarioBundle\Entity\InvLotes();
        $arLotes = $em->getRepository('zikmontInventarioBundle:InvLotes')->findOneBy(array('codigoItemFk' => $arMovimientoDetalle->getItemMD()->getCodigoItemPk()));
        if(count($arLotes) > 0) {
            $arMovimientoDetalle->setLoteFk($arLotes->getLoteFk());
            $arMovimientoDetalle->setCodigoBodegaFk($arLotes->getCodigoBodegaFk());
            $arMovimientoDetalle->setFechaVencimiento($arLotes->getFechaVencimiento());
            $em->persist($arMovimientoDetalle);
            $em->flush();             
        }
    }
    
    public function DevNroDetallesMovimiento($codigoMovimiento) {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
                ->select('COUNT(md.codigoDetalleMovimientoPk) as cantidad')
                ->from('zikmontInventarioBundle:InvMovimientosDetalles', 'md')
                ->where('md.codigoMovimientoFk = :codigoMovimientoFk')                
                ->setParameter('codigoMovimientoFk', $codigoMovimiento)
                ->getQuery();
        
        $arMovimientosDetalles = $query->getResult();
        return $arMovimientosDetalles[0]['cantidad'];
    }    
    
    public function DevMovimientosDetallesPendientesAfectar($codigoMovimiento) {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
                ->select('md')
                ->from('zikmontInventarioBundle:InvMovimientosDetalles', 'md')
                ->where('md.codigoMovimientoFk = :codigoMovimiento AND md.estadoCerrado = 0 AND md.estadoAutorizado = 1 AND (md.cantidad - md.cantidadAfectada) > 0')
                ->setParameter('codigoMovimiento', $codigoMovimiento)
                ->getQuery();

        $arMovimientosDetalles = $query->getResult();
        return $arMovimientosDetalles;
    } 
    
     /**
     * Devuelve un listado con los movimientos detalles pendientes segun filtro
     * @param integer $codigoDocumento
     * @param integer $codigoDocumentoTipo
     * @return array movimientos_detalles
     */
    public function DevMovimientosDetallesPendientes($codigoDocumento = null, $codigoDocumentoTipo = null) {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
                ->select('md')
                ->from('zikmontInventarioBundle:InvMovimientosDetalles', 'md')
                ->where('(md.cantidad - md.cantidadAfectada) > 0 AND md.estadoAutorizado = 1 AND md.estadoCerrado = 0')
                ->leftJoin("md.movimientoRel", "m");
        
        if ($codigoDocumento != Null && $codigoDocumento != "" && $codigoDocumento != 0)
            $query->andWhere('m.codigoDocumentoFk = ' . $codigoDocumento);

        if ($codigoDocumentoTipo != Null && $codigoDocumentoTipo != "" && $codigoDocumentoTipo != 0)
            $query->andWhere('m.codigoDocumentoTipoFk = ' . $codigoDocumentoTipo);
        
        $arMovimientosDetalles = $query->getQuery();

        return $arMovimientosDetalles->getResult();
    }    
    
    /**
     * Calcular el costo promedio
     * @param type $intExistenciaAnterior
     * @param type $intCantidadIngreso
     * @param type $douCostoPromedio
     * @param type $douCostoIngreso
     * @return int
     */
    public static function CacularCostoPromedio($intExistenciaAnterior = 0, $intCantidadIngreso = 0, $douCostoPromedio = 0, $douCostoIngreso = 0) {        
        $douCostoPromedioResultante = $douCostoIngreso;
        if($intExistenciaAnterior != 0)
            $douCostoPromedioResultante = (($intExistenciaAnterior * $douCostoPromedio) + (($intCantidadIngreso * $douCostoIngreso))) / $intExistenciaAnterior;        
        return $douCostoPromedioResultante;
    }    
 
    /**
     * Devuelve un array con el resumen (suma) subtotal de movimientos detalles
     * @param type $dateFechaDesde
     * @param type $dateFechaHasta
     * @param type $intItem
     */
    public function DevMovimientosDetallesResumen($dateFechaDesde = "", $dateFechaHasta, $intCodigoItem = "", $intCodigoDocumento = "", $intCodigoTipoDocumento = "") {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
                ->select('SUM(md.subTotal * doc.operacionComercial)')
                ->from('zikmontInventarioBundle:InvMovimientosDetalles', 'md')
                ->leftJoin("md.movimientoRel", "m")
                ->leftJoin("m.documentoRel", "doc")
                ->where('m.codigoDocumentoTipoFk = ' . $intCodigoTipoDocumento)
                ->orderBy("m.fecha", 'ASC');
        
        if ($dateFechaDesde != Null && $dateFechaDesde != "")
            $query->andWhere("m.fecha >= '" . $dateFechaDesde . " 00:00:00'");
        
        if ($dateFechaHasta != Null && $dateFechaHasta != "")
            $query->andWhere("m.fecha <= '" . $dateFechaHasta . " 23:59:59'");
        
        if($intCodigoItem != "")
            $query->andWhere("md.codigoItemFk = " . $intCodigoItem);
        
        $objQuery = $query->getQuery();        
        return $objQuery->getResult();        
    }
}