<?php

namespace zikmont\InventarioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UnidadesMedidaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvUnidadesMedidaRepository extends EntityRepository
{
}