<?php

namespace zikmont\GestionCarteraBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CompromisosPagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompromisosPagoRepository extends EntityRepository
{
}