<?php

namespace zikmont\GestionCarteraBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RegistroGestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistroGestionRepository extends EntityRepository
{
}