<?php

namespace zikmont\FrontEndBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConsecutivosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenConsecutivosRepository extends EntityRepository
{
    public function DevConsecutivo ($strConsecutivo) {
        $em = $this->getEntityManager();
        $intConsecutivo = 0;
        $arConsecutivos = new \zikmont\FrontEndBundle\Entity\Consecutivos();
        $arConsecutivos = $em->getRepository('zikmontFrontEndBundle:Consecutivos')->find(1);
        switch ($strConsecutivo) {
            case "Asientos";
                $intConsecutivo = $arConsecutivos->getAsientos();
                $arConsecutivos->setAsientos($intConsecutivo + 1);
                $em->persist($arConsecutivos);
                $em->flush();
            break;
        }        
        return $intConsecutivo;
    }    
}