<?php

namespace zikmont\FrontEndBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EmpresasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenEmpresasRepository extends EntityRepository
{
}