<?php

namespace zikmont\FrontEndBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TercerosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenTercerosRepository extends EntityRepository
{
    public function BuscarTerceros() {
        $em = $this->getEntityManager();
        $arTerceros = new \zikmont\FrontEndBundle\Entity\GenTerceros();
        $arTerceros = $em->getRepository('zikmontFrontEndBundle:GenTerceros')->findAll();

        return $arTerceros;
    }   
    
    /**
     * Busca los productos que coincida a la descripcion enviada por parametro
     * @param string $strNombreTercero El nombre del tercero a buscar
     * @return query el resultado de la busqueda. 
     */
    public function BuscarNombreTercero($strNombreTercero) {
        try {
            $em = $this->getEntityManager();
            $query = $em->createQueryBuilder()
                    ->select('tercero')
                    ->from('zikmontFrontEndBundle:GenTerceros', 'tercero')
                    ->where($em->createQueryBuilder()->expr()->like('tercero.nombreCortoTercero', $em->createQueryBuilder()->expr()->literal('%' . $strNombreTercero . '%')))
                    ->orWhere($em->createQueryBuilder()->expr()->like('tercero.codigoTerceroPk', $em->createQueryBuilder()->expr()->literal('%' . $strNombreTercero . '%')))
                    ->getQuery();
            $arResultado = $query->getResult();
            $query->getSQL();
            return $arResultado;
        } catch (Exception $e) {
            return $e;
        }
    }

    public function BuscarCodigoTercero($intCodigoTercero) {
        
    }
    
    
    
}