login:
    pattern:   /login
    defaults:  { _controller: zikmontSeguridadBundle:Seguridad:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

registro:
    pattern:   /registro
    defaults:  { _controller: zikmontSeguridadBundle:Seguridad:registro }