parameters:
#    zikmont_seguridad.example.class: zikmont\SeguridadBundle\Example

services:
#    zikmont_seguridad.example:
#        class: %zikmont_seguridad.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
