<?php

namespace zikmont\PresupuestosCivilesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MovimientosCivilesPresupuestosItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PcvItemsRepository extends EntityRepository
{
}