<?php

namespace zikmont\PresupuestosCivilesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MovimientosCivilesPresupuestosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PcvMovimientosRepository extends EntityRepository
{
}