<?php

namespace zikmont\PresupuestosCivilesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MovimientosCivilesPresupuestosDetallesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PcvMovimientosDetallesRepository extends EntityRepository
{
    public function DevNroDetallesMovimiento($codigoMovimiento) {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
                ->select('COUNT(mcpd.codigoMovimientoCivilPresupuestoDetallePk) as cantidad')
                ->from('zikmontFrontEndBundle:MovimientosCivilesPresupuestosDetalles', 'mcpd')
                ->where('mcpd.codigoMovimientoCivilPresupuestoFk = :codigoMovimientoCivilPresupuestoFk')                
                ->setParameter('codigoMovimientoCivilPresupuestoFk', $codigoMovimiento)
                ->getQuery();
        
        $arMovimientosCivilesPresupuestosDetalles = $query->getResult();
        return $arMovimientosCivilesPresupuestosDetalles[0]['cantidad'];
    }     
}