<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class zikmontFrontEndBundleEntityMovimientosProxy extends \zikmont\FrontEndBundle\Entity\Movimientos implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getCodigoMovimientoPk()
    {
        $this->__load();
        return parent::getCodigoMovimientoPk();
    }

    public function setCodigoDocumentoTipoFk($codigoDocumentoTipoFk)
    {
        $this->__load();
        return parent::setCodigoDocumentoTipoFk($codigoDocumentoTipoFk);
    }

    public function getCodigoDocumentoTipoFk()
    {
        $this->__load();
        return parent::getCodigoDocumentoTipoFk();
    }

    public function setCodigoDocumentoFk($codigoDocumentoFk)
    {
        $this->__load();
        return parent::setCodigoDocumentoFk($codigoDocumentoFk);
    }

    public function getCodigoDocumentoFk()
    {
        $this->__load();
        return parent::getCodigoDocumentoFk();
    }

    public function setNumeroMovimiento($numeroMovimiento)
    {
        $this->__load();
        return parent::setNumeroMovimiento($numeroMovimiento);
    }

    public function getNumeroMovimiento()
    {
        $this->__load();
        return parent::getNumeroMovimiento();
    }

    public function setFecha($fecha)
    {
        $this->__load();
        return parent::setFecha($fecha);
    }

    public function getFecha()
    {
        $this->__load();
        return parent::getFecha();
    }

    public function setCodigoTerceroFk($codigoTerceroFk)
    {
        $this->__load();
        return parent::setCodigoTerceroFk($codigoTerceroFk);
    }

    public function getCodigoTerceroFk()
    {
        $this->__load();
        return parent::getCodigoTerceroFk();
    }

    public function setCodigoEmpresaFk($codigoEmpresaFk)
    {
        $this->__load();
        return parent::setCodigoEmpresaFk($codigoEmpresaFk);
    }

    public function getCodigoEmpresaFk()
    {
        $this->__load();
        return parent::getCodigoEmpresaFk();
    }

    public function setValorTotalIva($valorTotalIva)
    {
        $this->__load();
        return parent::setValorTotalIva($valorTotalIva);
    }

    public function getValorTotalIva()
    {
        $this->__load();
        return parent::getValorTotalIva();
    }

    public function setSubTotal($subTotal)
    {
        $this->__load();
        return parent::setSubTotal($subTotal);
    }

    public function getSubTotal()
    {
        $this->__load();
        return parent::getSubTotal();
    }

    public function setValorTotalDescuento($valorTotalDescuento)
    {
        $this->__load();
        return parent::setValorTotalDescuento($valorTotalDescuento);
    }

    public function getValorTotalDescuento()
    {
        $this->__load();
        return parent::getValorTotalDescuento();
    }

    public function setTotalNeto($totalNeto)
    {
        $this->__load();
        return parent::setTotalNeto($totalNeto);
    }

    public function getTotalNeto()
    {
        $this->__load();
        return parent::getTotalNeto();
    }

    public function setCodigoUsuarioFk($codigoUsuarioFk)
    {
        $this->__load();
        return parent::setCodigoUsuarioFk($codigoUsuarioFk);
    }

    public function getCodigoUsuarioFk()
    {
        $this->__load();
        return parent::getCodigoUsuarioFk();
    }

    public function setComentarios($comentarios)
    {
        $this->__load();
        return parent::setComentarios($comentarios);
    }

    public function getComentarios()
    {
        $this->__load();
        return parent::getComentarios();
    }

    public function setDocumentoRel(\zikmont\FrontEndBundle\Entity\Documentos $documentoRel)
    {
        $this->__load();
        return parent::setDocumentoRel($documentoRel);
    }

    public function getDocumentoRel()
    {
        $this->__load();
        return parent::getDocumentoRel();
    }

    public function setTerceroRel(\zikmont\FrontEndBundle\Entity\Terceros $terceroRel)
    {
        $this->__load();
        return parent::setTerceroRel($terceroRel);
    }

    public function getTerceroRel()
    {
        $this->__load();
        return parent::getTerceroRel();
    }

    public function setEstadoAutorizado($estadoAutorizado)
    {
        $this->__load();
        return parent::setEstadoAutorizado($estadoAutorizado);
    }

    public function getEstadoAutorizado()
    {
        $this->__load();
        return parent::getEstadoAutorizado();
    }

    public function setEstadoAnulado($estadoAnulado)
    {
        $this->__load();
        return parent::setEstadoAnulado($estadoAnulado);
    }

    public function getEstadoAnulado()
    {
        $this->__load();
        return parent::getEstadoAnulado();
    }

    public function setTotal($total)
    {
        $this->__load();
        return parent::setTotal($total);
    }

    public function getTotal()
    {
        $this->__load();
        return parent::getTotal();
    }

    public function setValorRetencionFuente($valorRetencionFuente)
    {
        $this->__load();
        return parent::setValorRetencionFuente($valorRetencionFuente);
    }

    public function getValorRetencionFuente()
    {
        $this->__load();
        return parent::getValorRetencionFuente();
    }

    public function setValorOtrasRetenciones($valorOtrasRetenciones)
    {
        $this->__load();
        return parent::setValorOtrasRetenciones($valorOtrasRetenciones);
    }

    public function getValorOtrasRetenciones()
    {
        $this->__load();
        return parent::getValorOtrasRetenciones();
    }

    public function setEstadoCerrado($estadoCerrado)
    {
        $this->__load();
        return parent::setEstadoCerrado($estadoCerrado);
    }

    public function getEstadoCerrado()
    {
        $this->__load();
        return parent::getEstadoCerrado();
    }

    public function setDocumentoTipoRel(\zikmont\FrontEndBundle\Entity\DocumentosTipo $documentoTipoRel)
    {
        $this->__load();
        return parent::setDocumentoTipoRel($documentoTipoRel);
    }

    public function getDocumentoTipoRel()
    {
        $this->__load();
        return parent::getDocumentoTipoRel();
    }

    public function setEstadoImpreso($estadoImpreso)
    {
        $this->__load();
        return parent::setEstadoImpreso($estadoImpreso);
    }

    public function getEstadoImpreso()
    {
        $this->__load();
        return parent::getEstadoImpreso();
    }

    public function setEstadoContabilizado($estadoContabilizado)
    {
        $this->__load();
        return parent::setEstadoContabilizado($estadoContabilizado);
    }

    public function getEstadoContabilizado()
    {
        $this->__load();
        return parent::getEstadoContabilizado();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'codigoMovimientoPk', 'codigoDocumentoTipoFk', 'codigoDocumentoFk', 'numeroMovimiento', 'fecha', 'codigoTerceroFk', 'codigoEmpresaFk', 'valorTotalIva', 'subTotal', 'valorTotalDescuento', 'total', 'valorRetencionFuente', 'valorOtrasRetenciones', 'codigoUsuarioFk', 'comentarios', 'estadoAutorizado', 'estadoImpreso', 'estadoCerrado', 'estadoAnulado', 'estadoContabilizado', 'documentoRel', 'terceroRel', 'documentoTipoRel');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}