<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class zikmontFrontEndBundleEntityConceptosRetencionesProxy extends \zikmont\FrontEndBundle\Entity\ConceptosRetenciones implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getCodigoConceptoRetencionPk()
    {
        $this->__load();
        return parent::getCodigoConceptoRetencionPk();
    }

    public function setNombreConceptoRetencion($nombreConceptoRetencion)
    {
        $this->__load();
        return parent::setNombreConceptoRetencion($nombreConceptoRetencion);
    }

    public function getNombreConceptoRetencion()
    {
        $this->__load();
        return parent::getNombreConceptoRetencion();
    }

    public function setReferencia($referencia)
    {
        $this->__load();
        return parent::setReferencia($referencia);
    }

    public function getReferencia()
    {
        $this->__load();
        return parent::getReferencia();
    }

    public function setCuentaContable($cuentaContable)
    {
        $this->__load();
        return parent::setCuentaContable($cuentaContable);
    }

    public function getCuentaContable()
    {
        $this->__load();
        return parent::getCuentaContable();
    }

    public function setPorcentajeConceptoRetencion($porcentajeConceptoRetencion)
    {
        $this->__load();
        return parent::setPorcentajeConceptoRetencion($porcentajeConceptoRetencion);
    }

    public function getPorcentajeConceptoRetencion()
    {
        $this->__load();
        return parent::getPorcentajeConceptoRetencion();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'codigoConceptoRetencionPk', 'nombreConceptoRetencion', 'porcentajeConceptoRetencion', 'referencia', 'cuentaContable');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}