<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class zikmontFrontEndBundleEntityTercerosProxy extends \zikmont\FrontEndBundle\Entity\Terceros implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getCodigoTerceroPk()
    {
        $this->__load();
        return parent::getCodigoTerceroPk();
    }

    public function setNombreCortoTercero($nombreCortoTercero)
    {
        $this->__load();
        return parent::setNombreCortoTercero($nombreCortoTercero);
    }

    public function getNombreCortoTercero()
    {
        $this->__load();
        return parent::getNombreCortoTercero();
    }

    public function setNombres($nombres)
    {
        $this->__load();
        return parent::setNombres($nombres);
    }

    public function getNombres()
    {
        $this->__load();
        return parent::getNombres();
    }

    public function setApellido1($apellido1)
    {
        $this->__load();
        return parent::setApellido1($apellido1);
    }

    public function getApellido1()
    {
        $this->__load();
        return parent::getApellido1();
    }

    public function setApellido2($apellido2)
    {
        $this->__load();
        return parent::setApellido2($apellido2);
    }

    public function getApellido2()
    {
        $this->__load();
        return parent::getApellido2();
    }

    public function setCodigoListaPrecioFk($codigoListaPrecioFk)
    {
        $this->__load();
        return parent::setCodigoListaPrecioFk($codigoListaPrecioFk);
    }

    public function getCodigoListaPrecioFk()
    {
        $this->__load();
        return parent::getCodigoListaPrecioFk();
    }

    public function setCodigoListaCostoFk($codigoListaCostoFk)
    {
        $this->__load();
        return parent::setCodigoListaCostoFk($codigoListaCostoFk);
    }

    public function getCodigoListaCostoFk()
    {
        $this->__load();
        return parent::getCodigoListaCostoFk();
    }

    public function setDireccion($direccion)
    {
        $this->__load();
        return parent::setDireccion($direccion);
    }

    public function getDireccion()
    {
        $this->__load();
        return parent::getDireccion();
    }

    public function setTelefono($telefono)
    {
        $this->__load();
        return parent::setTelefono($telefono);
    }

    public function getTelefono()
    {
        $this->__load();
        return parent::getTelefono();
    }

    public function setCelular($celular)
    {
        $this->__load();
        return parent::setCelular($celular);
    }

    public function getCelular()
    {
        $this->__load();
        return parent::getCelular();
    }

    public function setRetencionFuenteVentas($retencionFuenteVentas)
    {
        $this->__load();
        return parent::setRetencionFuenteVentas($retencionFuenteVentas);
    }

    public function getRetencionFuenteVentas()
    {
        $this->__load();
        return parent::getRetencionFuenteVentas();
    }

    public function setAutoretenedor($autoretenedor)
    {
        $this->__load();
        return parent::setAutoretenedor($autoretenedor);
    }

    public function getAutoretenedor()
    {
        $this->__load();
        return parent::getAutoretenedor();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'codigoTerceroPk', 'nombreCortoTercero', 'nombres', 'apellido1', 'apellido2', 'codigoListaPrecioFk', 'codigoListaCostoFk', 'direccion', 'telefono', 'celular', 'retencionFuenteVentas', 'autoretenedor');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}