<?php

namespace zikmont\TransporteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DespachosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TptDespachosRepository extends EntityRepository
{
}