<?php

namespace zikmont\TransporteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GuiasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TptGuiasRepository extends EntityRepository
{
}