<?php

namespace zikmont\GestionDocumentalBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AlertasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfiguracionDirectoriosDocumentosRepository extends EntityRepository
{
    public function DevCodigoConsecutivoArchivo() {
        try {
            $em = $this->getEntityManager();
            $query = $em->createQueryBuilder()
                    ->select('configuracion.codigoConsecutivoArchivo')
                    ->from('zikmontGestionDocumentalBundle:ConfiguracionDirectorios', 'configuracion')
                    ->orderBy('codigoConsecutivoArchivo', 'DESC')
                    ->getFirstResult()
                    ->getQuery();
            $arResultado = $query->getResult();
            return $arResultado+1;
        } catch (Exception $e) {
            return $e;
        }
    } 
}