<?php

namespace zikmont\GestionDocumentalBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AlertasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DirectoriosDocumentosRepository extends EntityRepository
{
    public function DevSubDirectorios($codigoDirectorio) {
        $em = $this->getEntityManager();         
        $arDirectorios = new \zikmont\GestionDocumentalBundle\Entity\DirectoriosDocumentos();
        $arDirectorios = $em->getRepository('zikmontGestionDocumentalBundle:DirectoriosDocumentos')->findBy(array('codigoDirectorioPadreFk'=>$codigoDirectorio));         
        return $arDirectorios;        
    }     
}