<?php

namespace zikmont\GestionDocumentalBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AlertasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentosDigitalizadosRepository extends EntityRepository
{
    
}