parameters:
#    zikmont_gestion_cartera.example.class: zikmont\GestionCarteraBundle\Example

services:
#    zikmont_gestion_cartera.example:
#        class: %zikmont_gestion_cartera.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
