<?php

namespace zikmont\TesoreriaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CuentasPagarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TesCuentasPagarRepository extends EntityRepository
{
    /**
     * Aplicar tesoreria: Este metodo efectua el movimiento de tesoreria respectivo para un movimiento
     * @param integer $codigoMovimiento Codigo del movimiento
     * */
    public function Aplicar($codigoMovimiento) { 
        $em = $this->getEntityManager();
        $arMovimiento = new \zikmont\InventarioBundle\Entity\InvMovimientos();        
        $arMovimiento = $em->getRepository('zikmontInventarioBundle:InvMovimientos')->find($codigoMovimiento);
        $arCuentaPagar = new \zikmont\FrontEndBundle\Entity\CuentasPagar();
        $arCuentaPagar->setFecha($arMovimiento->getFecha());
        $arCuentaPagar->setMovimientoRel($arMovimiento);
        $arCuentaPagar->setTerceroRel($arMovimiento->getTerceroRel());
        $arCuentaPagar->setValorOriginal($arMovimiento->getTotal());          
        $arCuentaPagar->setSaldo($arMovimiento->getTotal());
        /*if($arMovimiento->getDocumentoRel()->getTipoAsientoTesoreria() == 1)
            $arCuentaPagar->setDebitos ($arMovimiento->getTotal());
        
        if($arMovimiento->getDocumentoRel()->getTipoAsientoTesoreria() == 2)
            $arCuentaPagar->setCreditos($arMovimiento->getTotal());        
        */
        
        $em->persist($arCuentaPagar);
        $em->flush();                                  
    } 
    
    public function DevCuentasPagar () {
        $em = $this->getEntityManager();         
        $query = $em->createQueryBuilder()            
            ->select('(cp.saldo - cp.debitos) as saldo, cp.fecha, (CURRENT_DATE() - cp.fecha) as nroDias, m.numeroMovimiento, doc.abreviatura, ter.nombreCortoTercero')                
            ->from('zikmontFrontEndBundle:CuentasPagar', 'cp')
            ->leftJoin('cp.movimientoRel', 'm')
            ->leftJoin('m.documentoRel', 'doc')
            ->leftJoin('cp.terceroRel', 'ter')                
            ->getQuery();
        return $query->getResult();        
    }      
}