parameters:
#    zikmont_front_end.example.class: zikmont\FrontEndBundle\Example

services:
#    zikmont_front_end.example:
#        class: %zikmont_front_end.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
