parameters:
#    zikmont_gestion_documental.example.class: zikmont\GestionDocumentalBundle\Example

services:
#    zikmont_gestion_documental.example:
#        class: %zikmont_gestion_documental.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
