<?php

namespace zikmont\FrontEndBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AlertasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlertasRepository extends EntityRepository
{

    
    public function DevAlerta($codigoAlerta) {
        $em = $this->getEntityManager();         
        $arAlerta = new \zikmont\FrontEndBundle\Entity\Alertas();
        $arAlerta = $em->getRepository('zikmontFrontEndBundle:Alertas')->find($codigoAlerta);         
        return $arAlerta;        
    }     

    
}