parameters:
#    zikmont_inventario.example.class: zikmont\InventarioBundle\Example

services:
#    zikmont_inventario.example:
#        class: %zikmont_inventario.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
