parameters:
#    zikmont_transporte.example.class: zikmont\TransporteBundle\Example

services:
#    zikmont_transporte.example:
#        class: %zikmont_transporte.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
