<?php

namespace zikmont\ImpresionesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReportesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImpReportesRepository extends EntityRepository
{
}