parameters:
#    zikmont_mensajes.example.class: zikmont\MensajesBundle\Example

services:
#    zikmont_mensajes.example:
#        class: %zikmont_mensajes.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
