parameters:
#    zikmont_tesoreria.example.class: zikmont\TesoreriaBundle\Example

services:
#    zikmont_tesoreria.example:
#        class: %zikmont_tesoreria.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
